[package]
name = "imagecondenser"
version = "0.1.0"
edition = "2021"
authors = ["Turtleb01"]

[profile.release]
opt-level = 3

[profile.dev]
opt-level = 3

[dependencies]
image = "0.23.14"
clap = "2.33.3"
